### PR TITLE
Update dsc name

### PR DESCRIPTION
**Pull request by ChughShilpa**
## Description
This PR brings 2 changes:
1. Update dsc name to "default-dsc"
2. Remove test-odh from Makefile as this folder is no longer present

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by astefanutti — APPROVED** [review]
LGTM, thanks!

**Comment by astefanutti** [comment]
@ChughShilpa just checking, should this go upstream, or amend an existing patch we have in the ODH fork?

**Comment by ChughShilpa** [comment]
> @ChughShilpa just checking, should this go upstream, or amend an existing patch we have in the ODH fork?

In upstream
1. There is no "test-odh" in Makefile
2. dsc name is already updated in https://github.com/project-codeflare/codeflare-operator/blob/main/contrib/configuration/odh/default-dsc.yaml#L10

**Review by sutaakar — APPROVED** [review]

**Comment by astefanutti** [comment]
@ChughShilpa thanks.

/hold cancel

**Pull request merged**
