### PR TITLE
fix(manifestst): remove empty CRD folder and reference

### PR DESCRIPTION
**Pull request by zdtsw**
fix code sync from upstream [c771aae](https://github.com/opendatahub-io/codeflare-operator/commit/c771aae4dc990526b8b3b4d3817805fa479bded2) which is causing kustomize failing and ODH opeartor not functional 

error:
`Error: accumulating resources: accumulation err='accumulating resources from '../crd': '...../codeflare/crd' must resolve to a file': couldn't make target for path '.../codeflare/crd': kustomization.yaml is empty
`
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by zdtsw** [comment]
@anishasthana / @dimakis we need fix for this, it is blocking operator PR tests and will be for odh-nightly too

**Comment by anishasthana** [comment]
Cc @dimakis @sutaakar @ChristianZaccaria can you look at this when you're on tomorrow? Looks like we have a CVE issue as well -- we will need to take these changes downstream too, to the right release branch.

**Review by sutaakar — APPROVED** [review]

**Comment by zdtsw** [comment]
if we would like sync, can have this PR closed and get it from upstream https://github.com/project-codeflare/codeflare-operator/pull/504

**Pull request closed without merging**
