### PR TITLE
remove cf nb

### PR DESCRIPTION
**Pull request by KPostOffice**
## Description
https://github.com/red-hat-data-services/codeflare-operator/issues/3

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by anishasthana — APPROVED** [review]
/lgtm

**Review by sutaakar — APPROVED** [review]
/lgtm

**Comment by sutaakar** [comment]
Merging manually (as OpenShift CI issue is still not addressed).

**Pull request merged**
