### PR TITLE
Head final

### PR DESCRIPTION
**Pull request by sutaakar**
## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by astefanutti — COMMENTED** [review]
I think patch 5fb136537c7ceb1d251229b4ab405e9cceadb122 can be dropped?

**Review by astefanutti — APPROVED** [review]
LGTM

**Comment by ChristianZaccaria** [comment]
Perhaps conflicts must be resolved before force pushing main. Other than that /lgtm

**Comment by astefanutti** [comment]
> Thinking whether we should use same branching approach as in https://github.com/opendatahub-io/kueue - main branch would point to upstream main, dev branch would carry additional changes.

We only need to make sure the downstream build configuration is updated accordingly so it builds from the `dev` branch.

**Pull request merged**
