### PR TITLE
CARRY: Check if ODH CFO image exists and build image if needed

### PR DESCRIPTION
**Pull request by sutaakar**
Build on top of https://github.com/project-codeflare/codeflare-operator/pull/545.
Will be squashed to existing commit once approved.

## Description

Build ODH CFO image if not found on Quay repository.

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by sutaakar** [comment]
@zdtsw FYI

**Comment by zdtsw** [comment]
> @zdtsw FYI

thanks @sutaakar 
just to help me understand your PR: it is to do a pre-check before start the new image build process, right?
then mine will still be applied but on a different case which is running in any case once config/* is changed.

**Comment by sutaakar** [comment]
@zdtsw The workflow is repurposed, with this change it is executed for every push into the main branch which modifies `config/manager/params.env` file.
First check verifies if image already exists on Quay. If exists then image build part is skipped. If not exist then image build is triggered, building new image.

As a result, every commit modifying image tag will trigger this workflow to rebuild the image.

**Comment by sutaakar** [comment]
Change pushed directly to main branch to keep number of ODH commits limited. Closing the PR.

**Pull request closed without merging**
